## Single Message Campaign [/single_message_campaigns/{id}]
A Single Message Campaign is the simplist of campaigns.  By default, when a message campaign is created with a `message_campaign_preset_id` value of `1`, a single message campaign is created.
