### Create New Message Version [POST]
Create a new message version.

Attribute | Description | Example
--:| ----|-----
subject|The subject of the email|"Email Subject"
reply_to|The email address that will serve as the reply to email address|"noreply@secondstreet.com"
from_name|The name that is displayed in the from field|"No Reply"
body|This is the body of your message campaign. URL encoded? The body must contain the opt out token {{{System.OptOutText}}}|"\ntest\n\n{{{System.OptOutText}}}"
plain_text_body|This is the body of your message campaign that users will see if they view email in plain text |This is plain.
body_source_type_id|<table><tr><th>Name</th><th>ID</th></tr><tr><td>Template<td>1</td></tr><tr><td>Scrape Url<td>2</td></tr><tr><td>Html<td>3</td></tr></table>|1
body_scrape_url|The url if the message body type is scrape|"http://secondstreet.com/"
status_type_id|<table><tr><th>Name</th><th>ID</th></tr><tr><td>Active<td>1</td></tr><tr><td>InActive<td>2</td></tr><tr><td>Deleted<td>3</td></tr><tr><td>Submitted<td>4</td></tr><tr><td>Hidden<td>5</td></tr><tr><td>Rejected<td>6</td></tr><tr><td>Cancelled<td>7</td></tr></table>|1
sender_account_id|The id of a sender account for your organization|785
single_message_campaign_id|The id of the single message campaign|2273
message_id|The id of the message campaign|2467
message_body_template_id|The id of the template being used for the body if `body_source_type_id` has a value of `3`|1

+ Request with body (application/json)
    + Header

            Authorization: a1b2c3d4
            X-Api-Key:12345678
            X-Organization-Id:123

    + Body

            {
               "message-versions":[
                  {
                     "subject":"Email Subject",
                     "reply_to":"noreply@secondstreet.com",
                     "from_name":"No Reply",
                     "body":"\ntest\n\n{{{System.OptOutText}}}",
                     "plain_text_body":null,
                     "body_source_type_id":3,
                     "body_scrape_url":null,
                     "status_type_id":null,
                     "sender_account_id":"1",
                     "single_message_campaign_id":"2273",
                     "message_id":null,
                     "message_body_template_id":"1"
                  }
               ]
            }

+ Response 201

            {
               "message_versions":[
                  {
                     "body_source_type_id":3,
                     "embedded_errors":[

                     ],
                     "from_name":"No Reply",
                     "id":2647,
                     "message_body_template_id":1,
                     "message_id":2467,
                     "reply_to":"noreply@secondstreet.com",
                     "sender_account_id":1,
                     "single_message_campaign_id":2273,
                     "status_type_id":1,
                     "subject":"Subject Line Text"
                  }
               ]
            }
