### Create New Message Campaign [POST]

 Attribute | Description
 --:| ----
 message_campaign_preset_id | <table><tr><th>Name</th><th>ID</th></tr><tr><td>Single Email<td>1</td></tr><tr><td>Newsletter<td>2</td></tr><tr><td>Birthday<td>3</td></tr><tr><td>Drip Campaign<td>4</td></tr></table>

+ Request with body (application/json)

    + Header

            Authorization: a1b2c3d4
            X-Api-Key:12345678
            X-Organization-Id:123

    + Body

            {
              "message-campaigns":[
                {
                 "message_campaign_preset_id":1
                }
              ]
            }

+ Response 201

            {
              "message_campaigns": [
                {
                  "embedded_errors": [],
                  "id": "2273",
                  "is_legacy_message": false,
                  "is_setup_complete": false,
                  "message_campaign_type_id": 1,
                  "name": "EdwardsvilleOnline.com's Message Campaign 259",
                  "organization_id": 123,
                  "send_to_existing_audience_members": false,
                  "sending_status_type_id": 0,
                  "status_type_id": 1
                }
              ]
            }
